### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by 17673640425** [teashirtt/resume-analysis-system#1]
请问一下这个项目 需要怎样才能跑起来呢

**Comment by 17673640425** [comment]
可以识别PDF吗

**Comment by 17673640425** [comment]
要起后端的话 是需要fastapi express springboot 这三个都启动吗？

**Comment by teash1rt** [comment]
#### 如果只是想运行“简历解析”这个模块
你可以只运行`FastApi`和前端项目，其他的不用启动
先下载模型，然后根据`requirements.txt`下载相关依赖最后启动`FastApi`即可
前端启动可以参考`README.md`

#### 如果想要启动整个项目
你需要先部署`MySQL` `Redis` `MongoDB`这三个数据库，然后用`Sql`里面的文件分别创建 `MySQL`和`MongoDB`表
部署数据库是为了能够启动`Springboot`，你需要在`Springboot/src/main/resources`下建立`secrets.txt`并根据`yml`文件填入键值对

至于`Express`可以不需要启动，可以参考`README.md`中的解释，如果需要启动的话就把`docx2txt`那块的逻辑换成向`Express`请求即可

**Comment by teash1rt** [comment]
如果有需要的话可以通过QQ1223696764或微信18701611573交流
