### ISSUE TITLE
docx转txt

### ISSUE THREAD

**Issue by zsp13832086627** [teashirtt/resume-analysis-system#11]
作者您好：
    麻烦跟您请教下，这两种转换文件的方式在哪里进行切换呢。还有就是如果不使用mangodb是否可行。

**Comment by teash1rt** [comment]
转换文件可以看下 FastApi
/document.py 的部分
不用 mangodb 只会影响可视化和统计的模块，会报错但是理论上应该不会影响 springboot 的冷启
