### ISSUE TITLE
FastAPI启动失败

### ISSUE THREAD

**Issue by zsp13832086627** [teashirtt/resume-analysis-system#13]
作者您好：
   我后续按照文档中的说明，下载了模型，并且放到了对应位置下，在执行python script.py 后启动了服务，上传文件后进行解析却报500，这个是什么原因呢，期待收到您的答复。

**Comment by teash1rt** [comment]
有fastapi的相关日志嘛

**Comment by zsp13832086627** [comment]
> 有fastapi的相关日志嘛
没有，我是小白，不知道在哪里看。。

**Comment by teash1rt** [comment]
可以先根据[requirements.txt](https://github.com/teash1rt/resume-analysis-system/blob/master/FastApi/requirements.txt)检查下版本

**Comment by zsp13832086627** [comment]
好的，谢谢

**Comment by teash1rt** [comment]
如果有相关日志或问题可以再提一个具体的issue
如果有交流的需要可以看第一个issue

**Comment by zsp13832086627** [comment]
好的，我试下是不是py版本问题，当前是3.8的，在另一台电脑使用3.11的没有问题了
