### ISSUE TITLE
大佬，网盘链接失效了

### ISSUE THREAD

**Issue by Yumetski** [teashirtt/resume-analysis-system#4]
可以用百度云盘快传，就不怕失效了

**Comment by Yumetski** [comment]
还想请问下那个train目录下就是训练的jupyter文件吗？

**Comment by teash1rt** [comment]
> 可以用百度云盘快传，就不怕失效了

看了下感觉可能不太方便
新的链接已经更新了

**Comment by teash1rt** [comment]
> 还想请问下那个train目录下就是训练的jupyter文件吗？

训练的代码都在对应的 jupyter 里

**Comment by Yumetski** [comment]
谢谢大佬了
